---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-service-dns-exporter
  namespace: tool
spec:
  replicas: 1
  selector:
    matchLabels:
      application: kube-service-dns-exporter
  template:
    metadata:
      labels:
        application: kube-service-dns-exporter
    spec:
      serviceAccountName: kopf
      containers:
        - name: kube-service-dns-exporter
          image: email2liyang/kube_service_dns_exporter
          env:
            - name: hosted_zone_id
              valueFrom:
                secretKeyRef:
                  name: kopf-secret
                  key: hosted_zone_id
            - name: aws_access_key_id
              valueFrom:
                secretKeyRef:
                  name: kopf-secret
                  key: aws_access_key_id
            - name: aws_secret_access_key
              valueFrom:
                secretKeyRef:
                  name: kopf-secret
                  key: aws_secret_access_key
            - name: domain_name
              value: vipmind.me
            - name: domain_prefix
              value: kube