---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: tool
  name: kopf
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: kopf-role-cluster
rules:

  # Framework: knowing which other operators are running (i.e. peering).
  - apiGroups: [zalando.org]
    resources: [clusterkopfpeerings]
    verbs: [list, watch, patch, get]
  - apiGroups: [apiextensions.k8s.io]
    resources: [customresourcedefinitions]
    verbs: [list, get]
  # Framework: cluster wide access to create/patch event resources
  - apiGroups: [events.k8s.io]
    resources: [events]
    verbs: [create, patch]
  - apiGroups: [""]
    resources: [events]
    verbs: [create, patch]

  # Application: cluster-wide access.
  - apiGroups: [""]
    resources: [services]
    verbs: [get, list, create, update, patch, watch]


---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: kopf-rolebinding-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kopf-role-cluster
subjects:
  - kind: ServiceAccount
    name: kopf
    namespace: tool